{переменные для размещения каталога анализируемых баз}
{client.db}
{make.db}
{barter.db}
{agent.db}
{sklad.db}
{eksped.db - ее нужно конвертнуть для введения поля RCD : Boolean;}
{group.db  - ее нужно конвертнуть для введения поля RCD : Boolean;}
{region.db - ее нужно конвертнуть для введения поля RCD : Boolean;}

{
ввести в основной программе из ини файла
переменные префиксы видов почтовых пакетов
A - приходы
B - переоценки
C - client.db
E - make.db
F - barter.db
G - agent.db
H - sklad.db
I - eksped.db
E - group.db
K - region.db
}


{переменные для размещения каталога экспорта для каждого объекта}